[package]
name = "monopoly"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.14.2"
rand = "0.8.5"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
